"""Message table updated id field

Revision ID: 6ff35232ee9e
Revises: db27fed240bb
Create Date: 2025-09-10 16:05:05.580418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6ff35232ee9e'
down_revision: Union[str, None] = 'db27fed240bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'id',
               existing_type=mysql.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'id',
               existing_type=sa.Uuid(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
